// Mock data used when Supabase is not configured (or as fallback for empty queries).
import type { Property, AppUser, Inquiry } from "./types";

const PHOTOS = {
  house: [
    "https://images.unsplash.com/photo-1605352081508-2e09927ecfe3?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1531300365552-da5abe58a725?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1560184897-ae75f418493e?auto=format&fit=crop&w=1200&q=80",
  ],
  apartment: [
    "https://images.unsplash.com/photo-1626882920560-80b382db2bc9?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1652081577415-bfc04074328c?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
  ],
  land: [
    "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1623411579348-548e4c9d99fb?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1685222253612-0d6ee3487be2?auto=format&fit=crop&w=1200&q=80",
  ],
  commercial: [
    "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1572457403736-88ead9cf03ba?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1715026323282-073e1a65576a?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1685459143178-2c24b66d44df?auto=format&fit=crop&w=1200&q=80",
    "https://images.unsplash.com/photo-1694885169342-909981fb408a?auto=format&fit=crop&w=1200&q=80",
  ],
};

const mkImgs = (type: keyof typeof PHOTOS, offset = 0) =>
  [0, 1, 2].map((i) => PHOTOS[type][(offset + i) % PHOTOS[type].length]);

// ── Mock agents ───────────────────────────────────────────────────────────────
export const MOCK_AGENT: AppUser = {
  id: "agent-1",
  email: "agent@abodespot.com",
  role: "agent",
  is_verified: true,
  full_name: "Emeka Okafor",
  phone: "+234 803 456 7890",
  company_name: "Okafor Realty Group",
  avatar_url: null,
  created_at: new Date().toISOString(),
};

export const MOCK_AGENT_2: AppUser = {
  id: "agent-2",
  email: "agent2@abodespot.com",
  role: "agent",
  is_verified: true,
  full_name: "Fatima Bello",
  phone: "+234 805 234 5678",
  company_name: "Bello Properties Ltd",
  avatar_url: null,
  created_at: new Date().toISOString(),
};

// ── Mock buyers (used as inquiry senders) ────────────────────────────────────
const MOCK_BUYER_1: AppUser = {
  id: "user-demo",
  email: "buyer1@example.com",
  role: "user",
  is_verified: true,
  full_name: "Chidi Okeke",
  phone: "+234 701 234 5678",
  company_name: null,
  avatar_url: null,
  created_at: new Date().toISOString(),
};

const MOCK_BUYER_2: AppUser = {
  id: "user-demo-2",
  email: "buyer2@example.com",
  role: "user",
  is_verified: true,
  full_name: "Aisha Balogun",
  phone: "+234 812 987 6543",
  company_name: null,
  avatar_url: null,
  created_at: new Date().toISOString(),
};

const MOCK_BUYER_3: AppUser = {
  id: "user-demo-3",
  email: "buyer3@example.com",
  role: "user",
  is_verified: true,
  full_name: "Tunde Adeyemi",
  phone: "+234 903 111 2222",
  company_name: null,
  avatar_url: null,
  created_at: new Date().toISOString(),
};

// ── Properties ────────────────────────────────────────────────────────────────
export const MOCK_PROPERTIES: Property[] = [
  // ── HOUSES (4) ──
  {
    id: "p1",
    title: "Lekki Five-Bedroom Family Villa",
    description:
      "A move-in-ready family home in Lekki Phase 1 with practical living areas, secure parking, and access to everyday amenities.",
    price: 320000000,
    bedrooms: 5,
    bathrooms: 5,
    area_sqft: 4800,
    property_type: "house",
    listing_type: "sale",
    address: "Lekki Phase 1, Lagos",
    city: "Lekki Phase 1",
    state: "Lagos",
    zip_code: null,
    images: mkImgs("house", 0),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: true,
    views: 0,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p2",
    title: "Gwarinpa Four-Bedroom Detached Home",
    description:
      "A practical four-bedroom home in Gwarinpa with family living spaces, covered parking, and convenient access to daily services.",
    price: 85000000,
    bedrooms: 4,
    bathrooms: 3,
    area_sqft: 3200,
    property_type: "house",
    listing_type: "sale",
    address: "Gwarinpa, Abuja",
    city: "Gwarinpa",
    state: "Abuja",
    zip_code: null,
    images: mkImgs("house", 1),
    agent_id: MOCK_AGENT_2.id,
    status: "approved",
    featured: true,
    views: 0,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    agent: MOCK_AGENT_2,
  },
  {
    id: "p3",
    title: "Port Harcourt Three-Bedroom Family House",
    description:
      "A well-finished three-bedroom home in Port Harcourt with comfortable rooms, a neat compound, and broad access to everyday amenities.",
    price: 65000000,
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 2100,
    property_type: "house",
    listing_type: "sale",
    address: "Port Harcourt, Rivers",
    city: "Port Harcourt",
    state: "Rivers",
    zip_code: null,
    images: mkImgs("house", 2),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: false,
    views: 0,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p4",
    title: "Victoria Island Five-Bedroom Furnished Home",
    description:
      "A furnished five-bedroom home in Victoria Island with generous living areas, secure parking, and convenient access to business districts.",
    price: 18000000,
    bedrooms: 5,
    bathrooms: 6,
    area_sqft: 5500,
    property_type: "house",
    listing_type: "rent",
    address: "Victoria Island, Lagos",
    city: "Victoria Island",
    state: "Lagos",
    zip_code: null,
    images: mkImgs("house", 3),
    agent_id: MOCK_AGENT_2.id,
    status: "approved",
    featured: true,
    views: 0,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    agent: MOCK_AGENT_2,
  },

  // ── APARTMENTS (4) ──
  {
    id: "p5",
    title: "Eko Atlantic Two-Bedroom Apartment",
    description:
      "A modern two-bedroom apartment in Eko Atlantic with efficient room layouts, contemporary fittings, and convenient access to city services.",
    price: 195000000,
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 1650,
    property_type: "apartment",
    listing_type: "sale",
    address: "Eko Atlantic, Lagos",
    city: "Eko Atlantic",
    state: "Lagos",
    zip_code: null,
    images: mkImgs("apartment", 0),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: true,
    views: 0,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p6",
    title: "Ikoyi Three-Bedroom Serviced Apartment",
    description:
      "A serviced three-bedroom apartment in Ikoyi with modern fittings, efficient room flow, and practical shared amenities for city living.",
    price: 7500000,
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 2200,
    property_type: "apartment",
    listing_type: "rent",
    address: "Ikoyi, Lagos",
    city: "Ikoyi",
    state: "Lagos",
    zip_code: null,
    images: mkImgs("apartment", 1),
    agent_id: MOCK_AGENT_2.id,
    status: "approved",
    featured: false,
    views: 0,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    agent: MOCK_AGENT_2,
  },
  {
    id: "p7",
    title: "Wuse 2 One-Bedroom Apartment",
    description:
      "A compact one-bedroom apartment in Wuse 2 with a simple modern layout, suitable for city living and easy daily movement.",
    price: 2200000,
    bedrooms: 1,
    bathrooms: 1,
    area_sqft: 620,
    property_type: "apartment",
    listing_type: "rent",
    address: "Wuse 2, Abuja",
    city: "Wuse 2",
    state: "Abuja",
    zip_code: null,
    images: mkImgs("apartment", 2),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: false,
    views: 0,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p8",
    title: "Ikoyi Four-Bedroom Penthouse Apartment",
    description:
      "A large four-bedroom penthouse apartment in Ikoyi with generous living spaces, modern fittings, and practical access to nearby services.",
    price: 980000000,
    bedrooms: 4,
    bathrooms: 5,
    area_sqft: 6800,
    property_type: "apartment",
    listing_type: "sale",
    address: "Ikoyi, Lagos",
    city: "Ikoyi",
    state: "Lagos",
    zip_code: null,
    images: mkImgs("apartment", 3),
    agent_id: MOCK_AGENT_2.id,
    status: "approved",
    featured: true,
    views: 0,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    agent: MOCK_AGENT_2,
  },

  // ── LAND (3) ──
  {
    id: "p9",
    title: "Ajah Residential Plot",
    description:
      "A documented residential land opportunity around Ajah, suitable for residential planning subject to local approvals.",
    price: 28000000,
    bedrooms: null,
    bathrooms: null,
    area_sqft: 6458,
    property_type: "land",
    listing_type: "sale",
    address: "Ajah, Lagos",
    city: "Ajah",
    state: "Lagos",
    zip_code: null,
    images: mkImgs("land", 0),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: false,
    views: 0,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p10",
    title: "Maitama Residential Plot",
    description:
      "A documented residential land opportunity around Maitama, suitable for a private home or long-term planning subject to local approvals.",
    price: 180000000,
    bedrooms: null,
    bathrooms: null,
    area_sqft: 10764,
    property_type: "land",
    listing_type: "sale",
    address: "Maitama, Abuja",
    city: "Maitama",
    state: "Abuja",
    zip_code: null,
    images: mkImgs("land", 1),
    agent_id: MOCK_AGENT_2.id,
    status: "approved",
    featured: true,
    views: 0,
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    agent: MOCK_AGENT_2,
  },
  {
    id: "p11",
    title: "Epe Residential Land",
    description:
      "A broad residential land opportunity around Epe with room for long-term development planning subject to documentation and local approvals.",
    price: 12000000,
    bedrooms: null,
    bathrooms: null,
    area_sqft: 12917,
    property_type: "land",
    listing_type: "sale",
    address: "Epe, Lagos",
    city: "Epe",
    state: "Lagos",
    zip_code: null,
    images: mkImgs("land", 2),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: false,
    views: 0,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    agent: MOCK_AGENT,
  },

  // ── COMMERCIAL (3) ──
  {
    id: "p12",
    title: "Lagos Island Office Floor",
    description:
      "A functional office floor around Lagos Island suitable for professional services, operations teams, or client-facing business use.",
    price: 22000000,
    bedrooms: null,
    bathrooms: 4,
    area_sqft: 2500,
    property_type: "commercial",
    listing_type: "rent",
    address: "Lagos Island, Lagos",
    city: "Lagos Island",
    state: "Lagos",
    zip_code: null,
    images: mkImgs("commercial", 0),
    agent_id: MOCK_AGENT_2.id,
    status: "approved",
    featured: false,
    views: 0,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    agent: MOCK_AGENT_2,
  },
  {
    id: "p13",
    title: "Ikeja Retail Showroom",
    description:
      "A retail showroom around Ikeja suitable for display-led businesses, service brands, or customer-facing operations.",
    price: 9500000,
    bedrooms: null,
    bathrooms: 2,
    area_sqft: 1800,
    property_type: "commercial",
    listing_type: "rent",
    address: "Ikeja, Lagos",
    city: "Ikeja",
    state: "Lagos",
    zip_code: null,
    images: mkImgs("commercial", 1),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: false,
    views: 0,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p14",
    title: "Wuse Commercial Plaza",
    description:
      "A commercial plaza around Wuse suitable for retail, office, or service-led tenants with practical access routes.",
    price: 750000000,
    bedrooms: null,
    bathrooms: 6,
    area_sqft: 8500,
    property_type: "commercial",
    listing_type: "sale",
    address: "Wuse, Abuja",
    city: "Wuse",
    state: "Abuja",
    zip_code: null,
    images: mkImgs("commercial", 2),
    agent_id: MOCK_AGENT_2.id,
    status: "approved",
    featured: true,
    views: 0,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    agent: MOCK_AGENT_2,
  },
];

// ── Inquiries ─────────────────────────────────────────────────────────────────
// Covers both sides:
//  - "user" scope → filters to user_id === "user-demo"    (buyer's dashboard)
//  - "agent" scope → shown to agents (all inquiries in mock)
//  - "admin" scope → all inquiries
export const MOCK_INQUIRIES: Inquiry[] = [
  // Buyer 1 (user-demo) sent these — shown on USER dashboard
  {
    id: "i1",
    property_id: "p1",
    user_id: MOCK_BUYER_1.id,
    message:
      "Good day. I am interested in scheduling a viewing for this duplex. What days are you available this week?",
    status: "unread",
    created_at: new Date().toISOString(),
    property: MOCK_PROPERTIES[0],   // p1 — belongs to MOCK_AGENT (agent-1)
    user: MOCK_BUYER_1,
  },
  {
    id: "i2",
    property_id: "p5",
    user_id: MOCK_BUYER_1.id,
    message:
      "Is the price of the Eko Atlantic apartment negotiable? I am a cash buyer ready to close within 2 weeks.",
    status: "replied",
    created_at: new Date(Date.now() - 86400000).toISOString(),
    property: MOCK_PROPERTIES[4],  // p5 — belongs to MOCK_AGENT (agent-1)
    user: MOCK_BUYER_1,
  },
  {
    id: "i3",
    property_id: "p7",
    user_id: MOCK_BUYER_1.id,
    message:
      "Does the Wuse 2 apartment come with a generator? What is the annual service charge?",
    status: "read",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    property: MOCK_PROPERTIES[6],  // p7 — belongs to MOCK_AGENT (agent-1)
    user: MOCK_BUYER_1,
  },

  // Buyer 2 sent these — also appear on AGENT dashboard for agent-1's properties
  {
    id: "i4",
    property_id: "p9",
    user_id: MOCK_BUYER_2.id,
    message:
      "Hello, is the Ajah land still available? I have a C of O query I'd like to discuss with you.",
    status: "unread",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    property: MOCK_PROPERTIES[8],  // p9 — belongs to MOCK_AGENT (agent-1)
    user: MOCK_BUYER_2,
  },
  {
    id: "i5",
    property_id: "p13",
    user_id: MOCK_BUYER_2.id,
    message:
      "We are looking to lease the Ikeja showroom for a fashion retail business. Can we arrange a site inspection?",
    status: "unread",
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    property: MOCK_PROPERTIES[12], // p13 — belongs to MOCK_AGENT (agent-1)
    user: MOCK_BUYER_2,
  },

  // Buyer 3 sent these — appear on AGENT-2's dashboard
  {
    id: "i6",
    property_id: "p2",
    user_id: MOCK_BUYER_3.id,
    message:
      "Good morning. Is the Gwarinpa home still available? I'd like to arrange a viewing this Saturday.",
    status: "read",
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    property: MOCK_PROPERTIES[1],  // p2 — belongs to MOCK_AGENT_2 (agent-2)
    user: MOCK_BUYER_3,
  },
  {
    id: "i7",
    property_id: "p8",
    user_id: MOCK_BUYER_3.id,
    message:
      "I'm interested in the Ikoyi penthouse. What documents are available and is there a payment plan option?",
    status: "replied",
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    property: MOCK_PROPERTIES[7],  // p8 — belongs to MOCK_AGENT_2 (agent-2)
    user: MOCK_BUYER_3,
  },
];
