// Mock data used when Supabase is not configured (or as fallback for empty queries).
// Replace by querying the real `properties` table once your DB is seeded.
import type { Property, AppUser, Inquiry } from "./types";

const PHOTOS = {
  house: [
    "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200",
    "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200",
    "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200",
    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200",
  ],
  apartment: [
    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200",
    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200",
    "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200",
    "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200",
  ],
  land: [
    "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200",
    "https://images.unsplash.com/photo-1549517045-bc93de075e53?w=1200",
    "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200",
  ],
  commercial: [
    "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200",
    "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200",
    "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1200",
  ],
};

const mkImgs = (type: keyof typeof PHOTOS, offset = 0) =>
  [0, 1, 2].map((i) => PHOTOS[type][(offset + i) % PHOTOS[type].length]);

export const MOCK_AGENT: AppUser = {
  id: "agent-1",
  email: "agent@abodespot.com",
  role: "agent",
  is_verified: true,
  full_name: "Emeka Okafor",
  phone: "+234 803 456 7890",
  company_name: "Okafor Realty Group",
  avatar_url: null,
  created_at: new Date().toISOString(),
};

export const MOCK_AGENT_2: AppUser = {
  id: "agent-2",
  email: "agent2@abodespot.com",
  role: "agent",
  is_verified: true,
  full_name: "Fatima Bello",
  phone: "+234 805 234 5678",
  company_name: "Bello Properties Ltd",
  avatar_url: null,
  created_at: new Date().toISOString(),
};

export const MOCK_PROPERTIES: Property[] = [
  // ── HOUSES ──
  {
    id: "p1",
    title: "Luxury 5-Bedroom Detached Duplex, Lekki Phase 1",
    description:
      "Exquisite duplex on a serene street in Lekki Phase 1. Features marble flooring, a fitted kitchen, BQ quarters, swimming pool, and 24/7 security. Perfect for executives and families.",
    price: 320000000,
    bedrooms: 5,
    bathrooms: 5,
    area_sqft: 4800,
    property_type: "house",
    listing_type: "sale",
    address: "14 Admiralty Way",
    city: "Lekki",
    state: "Lagos",
    zip_code: "106104",
    images: mkImgs("house", 0),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: true,
    views: 892,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p2",
    title: "4-Bedroom Terrace, Gwarinpa Estate, Abuja",
    description:
      "Spacious 4-bedroom terrace with well-landscaped compound, modern kitchen, and covered parking. Located in the serene Gwarinpa Estate with excellent road networks.",
    price: 85000000,
    bedrooms: 4,
    bathrooms: 3,
    area_sqft: 3200,
    property_type: "house",
    listing_type: "sale",
    address: "5 3rd Avenue",
    city: "Gwarinpa",
    state: "Abuja",
    zip_code: "900108",
    images: mkImgs("house", 1),
    agent_id: MOCK_AGENT_2.id,
    status: "approved",
    featured: true,
    views: 634,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    agent: MOCK_AGENT_2,
  },
  {
    id: "p3",
    title: "3-Bedroom Semi-Detached Bungalow, New GRA, Port Harcourt",
    description:
      "Well-finished semi-detached bungalow in the prestigious New GRA area. Features 3 ensuite bedrooms, a spacious living room, modern kitchen, and a neat compound.",
    price: 65000000,
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 2100,
    property_type: "house",
    listing_type: "sale",
    address: "22 Stadium Road",
    city: "Port Harcourt",
    state: "Rivers",
    zip_code: "500001",
    images: mkImgs("house", 2),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: false,
    views: 412,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p4",
    title: "Furnished 5-Bedroom Villa For Rent, Victoria Island",
    description:
      "Exquisitely furnished smart home on a quiet cul-de-sac in Victoria Island. Comes with top-of-the-range appliances, home cinema, and dedicated study rooms.",
    price: 18000000,
    bedrooms: 5,
    bathrooms: 6,
    area_sqft: 5500,
    property_type: "house",
    listing_type: "rent",
    address: "9 Kingsway Road",
    city: "Victoria Island",
    state: "Lagos",
    zip_code: "101241",
    images: mkImgs("house", 3),
    agent_id: MOCK_AGENT_2.id,
    status: "approved",
    featured: true,
    views: 1023,
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    agent: MOCK_AGENT_2,
  },

  // ── APARTMENTS ──
  {
    id: "p5",
    title: "2-Bedroom Luxury Apartment, Eko Atlantic City",
    description:
      "Stunning sea-view apartment in the brand new Eko Atlantic development. Floor-to-ceiling glass windows, fully fitted kitchen, gym, and concierge service.",
    price: 195000000,
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 1650,
    property_type: "apartment",
    listing_type: "sale",
    address: "Plot 15 Ocean Drive",
    city: "Eko Atlantic",
    state: "Lagos",
    zip_code: "101223",
    images: mkImgs("apartment", 0),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: true,
    views: 1487,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p6",
    title: "Serviced 3-Bedroom Flat For Rent, Ikoyi",
    description:
      "High-floor serviced apartment in a modern complex in Old Ikoyi. Features 24/7 power, swimming pool, gym, security, and ample parking. Ideal for corporate tenants.",
    price: 7500000,
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 2200,
    property_type: "apartment",
    listing_type: "rent",
    address: "3 Bourdillon Road",
    city: "Ikoyi",
    state: "Lagos",
    zip_code: "101223",
    images: mkImgs("apartment", 1),
    agent_id: MOCK_AGENT_2.id,
    status: "approved",
    featured: false,
    views: 765,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    agent: MOCK_AGENT_2,
  },
  {
    id: "p7",
    title: "1-Bedroom Studio Apartment, Wuse 2, Abuja",
    description:
      "Cozy, well-maintained studio apartment in the heart of Wuse 2. Ideal for young professionals. Features modern bathroom, 24hr security, and reliable power supply.",
    price: 2200000,
    bedrooms: 1,
    bathrooms: 1,
    area_sqft: 620,
    property_type: "apartment",
    listing_type: "rent",
    address: "Plot 22 IBB Way",
    city: "Wuse 2",
    state: "Abuja",
    zip_code: "900104",
    images: mkImgs("apartment", 2),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: false,
    views: 298,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p8",
    title: "4-Bedroom Penthouse, Banana Island",
    description:
      "Ultra-luxury penthouse spanning the entire top floor of an exclusive tower on Banana Island. Private rooftop terrace, private lift, and panoramic ocean views.",
    price: 980000000,
    bedrooms: 4,
    bathrooms: 5,
    area_sqft: 6800,
    property_type: "apartment",
    listing_type: "sale",
    address: "Block D, Banana Island",
    city: "Ikoyi",
    state: "Lagos",
    zip_code: "101223",
    images: mkImgs("apartment", 3),
    agent_id: MOCK_AGENT_2.id,
    status: "approved",
    featured: true,
    views: 2341,
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    agent: MOCK_AGENT_2,
  },

  // ── LAND ──
  {
    id: "p9",
    title: "600 sqm Dry Land, Sangotedo, Ajah",
    description:
      "600 square metres of dry, well-documented land in fast-developing Sangotedo. C of O available. Perfect for residential or investment development.",
    price: 28000000,
    bedrooms: null,
    bathrooms: null,
    area_sqft: 6458,
    property_type: "land",
    listing_type: "sale",
    address: "Opposite Shoprite, Sangotedo",
    city: "Ajah",
    state: "Lagos",
    zip_code: "106104",
    images: mkImgs("land", 0),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: false,
    views: 187,
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p10",
    title: "1,000 sqm Corner Piece, Maitama, Abuja",
    description:
      "Prime 1,000 sqm corner-piece land in the prestigious Maitama district. All documents intact including Survey Plan and Deed of Assignment. Great for a luxury home.",
    price: 180000000,
    bedrooms: null,
    bathrooms: null,
    area_sqft: 10764,
    property_type: "land",
    listing_type: "sale",
    address: "Plot 45 Bangui Street",
    city: "Maitama",
    state: "Abuja",
    zip_code: "900001",
    images: mkImgs("land", 1),
    agent_id: MOCK_AGENT_2.id,
    status: "approved",
    featured: true,
    views: 543,
    created_at: new Date(Date.now() - 9 * 86400000).toISOString(),
    agent: MOCK_AGENT_2,
  },
  {
    id: "p11",
    title: "2 Plots of Land, Epe Extension, Lagos",
    description:
      "Two plots of land (approximately 1,200 sqm total) with Government Consent in an estate with good road access in Epe. Suitable for residential, poultry, or mixed development.",
    price: 12000000,
    bedrooms: null,
    bathrooms: null,
    area_sqft: 12917,
    property_type: "land",
    listing_type: "sale",
    address: "Araga Estate",
    city: "Epe",
    state: "Lagos",
    zip_code: "106101",
    images: mkImgs("land", 2),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: false,
    views: 94,
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
    agent: MOCK_AGENT,
  },

  // ── COMMERCIAL ──
  {
    id: "p12",
    title: "Open-Plan Office Floor, Marina, Lagos Island",
    description:
      "Full floor office space (2,500 sqft) in a Grade-A building on Lagos Marina. Fully fitted with raised floors, central AC, high-speed fibre, and a dedicated boardroom.",
    price: 22000000,
    bedrooms: null,
    bathrooms: 4,
    area_sqft: 2500,
    property_type: "commercial",
    listing_type: "rent",
    address: "10 Commercial Road, Marina",
    city: "Lagos Island",
    state: "Lagos",
    zip_code: "101003",
    images: mkImgs("commercial", 0),
    agent_id: MOCK_AGENT_2.id,
    status: "approved",
    featured: false,
    views: 326,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    agent: MOCK_AGENT_2,
  },
  {
    id: "p13",
    title: "Retail Showroom / Shop, Ikeja GRA",
    description:
      "1,800 sqft ground-floor retail space in a busy commercial building along Mobolaji Bank Anthony Way. High foot traffic, glass frontage, and ample parking.",
    price: 9500000,
    bedrooms: null,
    bathrooms: 2,
    area_sqft: 1800,
    property_type: "commercial",
    listing_type: "rent",
    address: "Mobolaji Bank Anthony Way",
    city: "Ikeja",
    state: "Lagos",
    zip_code: "100001",
    images: mkImgs("commercial", 1),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: false,
    views: 210,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p14",
    title: "Commercial Plaza For Sale, Wuse Market, Abuja",
    description:
      "Fully tenanted 3-storey commercial plaza in the heart of Wuse Market. Comprises 24 shops on ground floor, 12 offices on upper floors. Excellent ROI investment.",
    price: 750000000,
    bedrooms: null,
    bathrooms: 6,
    area_sqft: 8500,
    property_type: "commercial",
    listing_type: "sale",
    address: "Zone 5 Wuse Market",
    city: "Wuse",
    state: "Abuja",
    zip_code: "900003",
    images: mkImgs("commercial", 2),
    agent_id: MOCK_AGENT_2.id,
    status: "approved",
    featured: true,
    views: 889,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    agent: MOCK_AGENT_2,
  },
];

export const MOCK_INQUIRIES: Inquiry[] = [
  {
    id: "i1",
    property_id: "p1",
    user_id: "user-demo",
    message: "Good day. I am interested in scheduling a viewing for this duplex. What days are available?",
    status: "unread",
    created_at: new Date().toISOString(),
    property: MOCK_PROPERTIES[0],
  },
  {
    id: "i2",
    property_id: "p5",
    user_id: "user-demo",
    message: "Is the price of the Eko Atlantic apartment negotiable? I am a cash buyer.",
    status: "replied",
    created_at: new Date(Date.now() - 86400000).toISOString(),
    property: MOCK_PROPERTIES[4],
  },
  {
    id: "i3",
    property_id: "p6",
    user_id: "user-demo",
    message: "Does the Ikoyi flat come with a generator and what is the service charge per annum?",
    status: "read",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    property: MOCK_PROPERTIES[5],
  },
];
