// Mock data used when Supabase is not configured (or as fallback for empty queries).
// Replace by querying the real `properties` table once your DB is seeded.
import type { Property, AppUser, Inquiry } from "./types";

const PHOTOS = [
  "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200",
  "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200",
  "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200",
  "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200",
];

const mkImgs = (offset = 0) => [0, 1, 2].map((i) => PHOTOS[(offset + i) % PHOTOS.length]);

export const MOCK_AGENT: AppUser = {
  id: "agent-1",
  email: "agent@demo.com",
  role: "agent",
  is_verified: true,
  full_name: "Jane Carter",
  phone: "+1 (555) 123-4567",
  company_name: "Carter Realty",
  avatar_url: null,
  created_at: new Date().toISOString(),
};

export const MOCK_PROPERTIES: Property[] = [
  {
    id: "p1",
    title: "Modern Downtown Loft",
    description:
      "A stunning modern loft in the heart of downtown. Floor-to-ceiling windows, open floor plan, and rooftop access.",
    price: 850000,
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 1450,
    property_type: "apartment",
    listing_type: "sale",
    address: "123 Main St",
    city: "Austin",
    state: "TX",
    zip_code: "78701",
    images: mkImgs(0),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: true,
    views: 234,
    created_at: new Date().toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p2",
    title: "Spacious Family Home",
    description: "Beautiful 4-bedroom home with large backyard, perfect for families.",
    price: 1250000,
    bedrooms: 4,
    bathrooms: 3,
    area_sqft: 2800,
    property_type: "house",
    listing_type: "sale",
    address: "456 Oak Ave",
    city: "Denver",
    state: "CO",
    zip_code: "80202",
    images: mkImgs(1),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: true,
    views: 412,
    created_at: new Date().toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p3",
    title: "Cozy Studio Apartment",
    description: "Charming studio in a quiet neighborhood. Recently renovated.",
    price: 1800,
    bedrooms: 1,
    bathrooms: 1,
    area_sqft: 550,
    property_type: "apartment",
    listing_type: "rent",
    address: "789 Pine Rd",
    city: "Seattle",
    state: "WA",
    zip_code: "98101",
    images: mkImgs(2),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: false,
    views: 98,
    created_at: new Date().toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p4",
    title: "Luxury Penthouse",
    description: "Panoramic city views from this top-floor penthouse.",
    price: 3200000,
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 3100,
    property_type: "apartment",
    listing_type: "sale",
    address: "1 Skyline Tower",
    city: "Miami",
    state: "FL",
    zip_code: "33131",
    images: mkImgs(3),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: true,
    views: 567,
    created_at: new Date().toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p5",
    title: "Commercial Office Space",
    description: "Prime commercial space in business district.",
    price: 8500,
    bedrooms: null,
    bathrooms: 2,
    area_sqft: 2200,
    property_type: "commercial",
    listing_type: "rent",
    address: "500 Business Pkwy",
    city: "Chicago",
    state: "IL",
    zip_code: "60601",
    images: mkImgs(4),
    agent_id: MOCK_AGENT.id,
    status: "approved",
    featured: false,
    views: 145,
    created_at: new Date().toISOString(),
    agent: MOCK_AGENT,
  },
  {
    id: "p6",
    title: "Buildable Land Lot",
    description: "5-acre lot with utilities, ready to build.",
    price: 425000,
    bedrooms: null,
    bathrooms: null,
    area_sqft: 217800,
    property_type: "land",
    listing_type: "sale",
    address: "Lot 12 Country Rd",
    city: "Boulder",
    state: "CO",
    zip_code: "80301",
    images: mkImgs(5),
    agent_id: MOCK_AGENT.id,
    status: "pending",
    featured: false,
    views: 32,
    created_at: new Date().toISOString(),
    agent: MOCK_AGENT,
  },
];

export const MOCK_INQUIRIES: Inquiry[] = [
  {
    id: "i1",
    property_id: "p1",
    user_id: "user-demo",
    message: "Hi, I'm interested in scheduling a viewing for this property.",
    status: "unread",
    created_at: new Date().toISOString(),
    property: MOCK_PROPERTIES[0],
  },
  {
    id: "i2",
    property_id: "p2",
    user_id: "user-demo",
    message: "Is the price negotiable?",
    status: "replied",
    created_at: new Date(Date.now() - 86400000).toISOString(),
    property: MOCK_PROPERTIES[1],
  },
];
