-- AbodeSpot schema entry point.
--
-- The canonical database schema now lives in the ordered migration chain:
--   supabase/migrations/
--
-- Apply it with:
--   supabase db push --linked
--
-- Do not use the old one-off SQL Editor script for this project. It was
-- incomplete for the current app code and did not include tables such as
-- agent_applications, participant-based conversations, and messages.
