/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedAgentInquiriesRouteImport } from './routes/_authenticated/agent/inquiries'
import { Route as AuthenticatedAgentEditIdRouteImport } from './routes/_authenticated/agent.edit.$id'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as AuthenticatedAdminAdminPropertiesRouteImport } from './routes/_authenticated/_admin/admin.properties'
import { Route as AuthenticatedAdminAdminInquiriesRouteImport } from './routes/_authenticated/_admin/admin.inquiries'
import { Route as AuthenticatedAdminAdminHomepageRouteImport } from './routes/_authenticated/_admin/admin.homepage'
import { Route as AuthenticatedAdminAdminFeaturedRouteImport } from './routes/_authenticated/_admin/admin.featured'
import { Route as AuthenticatedAdminAdminDashboardRouteImport } from './routes/_authenticated/_admin/admin.dashboard'
import { Route as AuthenticatedAdminAdminAddPropertyRouteImport } from './routes/_authenticated/_admin/admin.add-property'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentInquiriesRoute =
  AuthenticatedAgentInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAgentEditIdRoute =
  AuthenticatedAgentEditIdRouteImport.update({
    id: '/edit/$id',
    path: '/edit/$id',
    getParentRoute: () => AuthenticatedAgentRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminPropertiesRoute =
  AuthenticatedAdminAdminPropertiesRouteImport.update({
    id: '/admin/properties',
    path: '/admin/properties',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminInquiriesRoute =
  AuthenticatedAdminAdminInquiriesRouteImport.update({
    id: '/admin/inquiries',
    path: '/admin/inquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminHomepageRoute =
  AuthenticatedAdminAdminHomepageRouteImport.update({
    id: '/admin/homepage',
    path: '/admin/homepage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminFeaturedRoute =
  AuthenticatedAdminAdminFeaturedRouteImport.update({
    id: '/admin/featured',
    path: '/admin/featured',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminDashboardRoute =
  AuthenticatedAdminAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAddPropertyRoute =
  AuthenticatedAdminAdminAddPropertyRouteImport.update({
    id: '/admin/add-property',
    path: '/admin/add-property',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/properties': typeof PropertiesRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agent': typeof AuthenticatedAgentRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/property/$id': typeof PropertyIdRoute
  '/agent/inquiries': typeof AuthenticatedAgentInquiriesRoute
  '/admin/add-property': typeof AuthenticatedAdminAdminAddPropertyRoute
  '/admin/dashboard': typeof AuthenticatedAdminAdminDashboardRoute
  '/admin/featured': typeof AuthenticatedAdminAdminFeaturedRoute
  '/admin/homepage': typeof AuthenticatedAdminAdminHomepageRoute
  '/admin/inquiries': typeof AuthenticatedAdminAdminInquiriesRoute
  '/admin/properties': typeof AuthenticatedAdminAdminPropertiesRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/agent/edit/$id': typeof AuthenticatedAgentEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/properties': typeof PropertiesRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agent': typeof AuthenticatedAgentRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/property/$id': typeof PropertyIdRoute
  '/agent/inquiries': typeof AuthenticatedAgentInquiriesRoute
  '/admin/add-property': typeof AuthenticatedAdminAdminAddPropertyRoute
  '/admin/dashboard': typeof AuthenticatedAdminAdminDashboardRoute
  '/admin/featured': typeof AuthenticatedAdminAdminFeaturedRoute
  '/admin/homepage': typeof AuthenticatedAdminAdminHomepageRoute
  '/admin/inquiries': typeof AuthenticatedAdminAdminInquiriesRoute
  '/admin/properties': typeof AuthenticatedAdminAdminPropertiesRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/agent/edit/$id': typeof AuthenticatedAgentEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/properties': typeof PropertiesRoute
  '/register': typeof RegisterRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agent': typeof AuthenticatedAgentRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/property/$id': typeof PropertyIdRoute
  '/_authenticated/agent/inquiries': typeof AuthenticatedAgentInquiriesRoute
  '/_authenticated/_admin/admin/add-property': typeof AuthenticatedAdminAdminAddPropertyRoute
  '/_authenticated/_admin/admin/dashboard': typeof AuthenticatedAdminAdminDashboardRoute
  '/_authenticated/_admin/admin/featured': typeof AuthenticatedAdminAdminFeaturedRoute
  '/_authenticated/_admin/admin/homepage': typeof AuthenticatedAdminAdminHomepageRoute
  '/_authenticated/_admin/admin/inquiries': typeof AuthenticatedAdminAdminInquiriesRoute
  '/_authenticated/_admin/admin/properties': typeof AuthenticatedAdminAdminPropertiesRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/agent/edit/$id': typeof AuthenticatedAgentEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/properties'
    | '/register'
    | '/verify-email'
    | '/agent'
    | '/dashboard'
    | '/messages'
    | '/property/$id'
    | '/agent/inquiries'
    | '/admin/add-property'
    | '/admin/dashboard'
    | '/admin/featured'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/properties'
    | '/admin/users'
    | '/agent/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/properties'
    | '/register'
    | '/verify-email'
    | '/agent'
    | '/dashboard'
    | '/messages'
    | '/property/$id'
    | '/agent/inquiries'
    | '/admin/add-property'
    | '/admin/dashboard'
    | '/admin/featured'
    | '/admin/homepage'
    | '/admin/inquiries'
    | '/admin/properties'
    | '/admin/users'
    | '/agent/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/properties'
    | '/register'
    | '/verify-email'
    | '/_authenticated/_admin'
    | '/_authenticated/agent'
    | '/_authenticated/dashboard'
    | '/_authenticated/messages'
    | '/property/$id'
    | '/_authenticated/agent/inquiries'
    | '/_authenticated/_admin/admin/add-property'
    | '/_authenticated/_admin/admin/dashboard'
    | '/_authenticated/_admin/admin/featured'
    | '/_authenticated/_admin/admin/homepage'
    | '/_authenticated/_admin/admin/inquiries'
    | '/_authenticated/_admin/admin/properties'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/agent/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PropertiesRoute: typeof PropertiesRoute
  RegisterRoute: typeof RegisterRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent/inquiries': {
      id: '/_authenticated/agent/inquiries'
      path: '/inquiries'
      fullPath: '/agent/inquiries'
      preLoaderRoute: typeof AuthenticatedAgentInquiriesRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/agent/edit/$id': {
      id: '/_authenticated/agent/edit/$id'
      path: '/edit/$id'
      fullPath: '/agent/edit/$id'
      preLoaderRoute: typeof AuthenticatedAgentEditIdRouteImport
      parentRoute: typeof AuthenticatedAgentRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/properties': {
      id: '/_authenticated/_admin/admin/properties'
      path: '/admin/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AuthenticatedAdminAdminPropertiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/inquiries': {
      id: '/_authenticated/_admin/admin/inquiries'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AuthenticatedAdminAdminInquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/homepage': {
      id: '/_authenticated/_admin/admin/homepage'
      path: '/admin/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/featured': {
      id: '/_authenticated/_admin/admin/featured'
      path: '/admin/featured'
      fullPath: '/admin/featured'
      preLoaderRoute: typeof AuthenticatedAdminAdminFeaturedRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/dashboard': {
      id: '/_authenticated/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/add-property': {
      id: '/_authenticated/_admin/admin/add-property'
      path: '/admin/add-property'
      fullPath: '/admin/add-property'
      preLoaderRoute: typeof AuthenticatedAdminAdminAddPropertyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminAddPropertyRoute: typeof AuthenticatedAdminAdminAddPropertyRoute
  AuthenticatedAdminAdminDashboardRoute: typeof AuthenticatedAdminAdminDashboardRoute
  AuthenticatedAdminAdminFeaturedRoute: typeof AuthenticatedAdminAdminFeaturedRoute
  AuthenticatedAdminAdminHomepageRoute: typeof AuthenticatedAdminAdminHomepageRoute
  AuthenticatedAdminAdminInquiriesRoute: typeof AuthenticatedAdminAdminInquiriesRoute
  AuthenticatedAdminAdminPropertiesRoute: typeof AuthenticatedAdminAdminPropertiesRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminAddPropertyRoute:
    AuthenticatedAdminAdminAddPropertyRoute,
  AuthenticatedAdminAdminDashboardRoute: AuthenticatedAdminAdminDashboardRoute,
  AuthenticatedAdminAdminFeaturedRoute: AuthenticatedAdminAdminFeaturedRoute,
  AuthenticatedAdminAdminHomepageRoute: AuthenticatedAdminAdminHomepageRoute,
  AuthenticatedAdminAdminInquiriesRoute: AuthenticatedAdminAdminInquiriesRoute,
  AuthenticatedAdminAdminPropertiesRoute:
    AuthenticatedAdminAdminPropertiesRoute,
  AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAgentRouteChildren {
  AuthenticatedAgentInquiriesRoute: typeof AuthenticatedAgentInquiriesRoute
  AuthenticatedAgentEditIdRoute: typeof AuthenticatedAgentEditIdRoute
}

const AuthenticatedAgentRouteChildren: AuthenticatedAgentRouteChildren = {
  AuthenticatedAgentInquiriesRoute: AuthenticatedAgentInquiriesRoute,
  AuthenticatedAgentEditIdRoute: AuthenticatedAgentEditIdRoute,
}

const AuthenticatedAgentRouteWithChildren =
  AuthenticatedAgentRoute._addFileChildren(AuthenticatedAgentRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgentRoute: AuthenticatedAgentRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PropertiesRoute: PropertiesRoute,
  RegisterRoute: RegisterRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
